### PR TITLE
bumping up lodash to 3.3.0 allows to use the 'variable' option

### PR DESCRIPTION
**Pull request by gasp**
This 'variable' option is really useful in lodash templates

### CODE REVIEW

**Comment by ingro** [comment]
Could you please elaborate a little? Thanks

**Comment by gasp** [comment]
A very common pitfall with the _.template engine is that all values are mandatory.
If you have at template containing `<% one %>` and `<% two %>`, you have set `{one: 'une', two:'due'}` but as `_.template().source` is using `which` you cannot use this template with only `{one: 'une'}` parameter. This have been widely discussed in https://github.com/jashkenas/underscore/issues/237 .

A solution is to use  the `variable` option to avoid `ReferenceError` (please see https://github.com/jashkenas/underscore/issues/237#issuecomment-16336334 ).

Here is a sample gulpfile using this syntax that is not compatible with the old lodash lib.
```
var templater = template({
    variable: 'o'
  },
  namespace: '_templates',
  name: function (file) {
    var f = file.relative;
    // remove extension and 'templates/'
    f = f.substr(0, f.lastIndexOf('.')) || f;
    return f;
  }
});
```

**Comment by ingro** [comment]
Thanks for the clarification!

If I understand what you need I think you could already do it using the attribute `templateSettings` on the `options` object, which accepts the same values as the ones passed to lodash, like this:

```javascript
.pipe(template({
    templateSettings: {
        variable: 'o'
    }
}));
```

**Comment by gasp** [comment]
Exactly, but this was not supported in the "lodash.template": "~2.4.1"

**Comment by ingro** [comment]
Closed in favor of #8

**Pull request closed without merging**
